version: "3"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  server:
    build: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
