version: "3"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server
  server:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
