version: "3"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server1
      - server2
  server1:
    build: ./backend_flask_socketio
    ports:
      - "5000:5000"
    volumes:
      - ./backend_flask_socketio:/app
  server2:
    build: ./backend_python_socketio
    ports:
      - "8888:8888"
    volumes:
      - ./backend_python_socketio:/app
